server:
  port: 9000

spring:
  application:
    name: study2021
  cloud:
    sentinel:
      transport:
        dashboard: 10.170.160.123:8080
        port: 8719
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/appointment
    username: root
    password: toot
  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true

logging:
  level:
    root: info
    com.example.demo: info
#
#com:
#  xuyy:
#    name: 33
#    pass: 111

